server:
  port: 10086
spring:
  application:
    name: eurekaServer_10086
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:10087/eureka
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
